Optimized properties table when showing `all` properties
pimcore/studio-ui-bundle pull request #462
Opened 2024-08-12 09:41 UTC by Corepex

## Changes in this pull request
Resolves #331 
Blocked by: #461 

## Additional info

2024-08-13 06:45 UTC, markus-moser requested changes
@Corepex Thanks, I still found some editable items:

- [ ] drag&drop to asset relations is possible
- [ ] the inheritable checkbox is editable

Could you please check this? Afterwards I'd say it's fine!

2024-08-13 06:59 UTC, markus-moser commented
Separate issue for the headline topic #463

2024-08-16 06:43 UTC, vin0401 requested changes

2024-08-16 06:43 UTC, vin0401 commented on assets/js/src/core/modules/asset/editor/shared-tab-manager/tabs/properties/components/table/table.tsx
> +              <Button
Now where I see it, we could already implement the new Button with text and icon component here.

2024-08-16 06:56 UTC, vin0401 commented on assets/js/src/core/modules/asset/editor/shared-tab-manager/tabs/properties/components/table/table.tsx
> +              <Button
Ahhh, nevermind. :D  

I will refine the api of the button a bit more beforehand. ;D
So far it's not that compatible to ant design.

2024-08-20 08:24 UTC, merged