Update README.md
pimcore/studio-ui-bundle pull request #543
Opened 2024-09-20 06:35 UTC by ValeriaMaltseva

2024-09-20 06:43 UTC, ValeriaMaltseva commented
I have read the CLA Document and I hereby sign the CLA

2024-09-20 07:22 UTC, vin0401 requested changes

2024-09-20 07:22 UTC, vin0401 commented on README.md
> +#### Frontend UI: `{your-domain}/pimcore-studio`
I think we don't need the current admin domain here anymore.

This should be enough. :)
Admin UI: {your-domain}/pimcore-studio 

Also this step is not needed anymore:
- Login via the classic backend UI

Could you remove it? :) Christian already implemented the authentication for studio. So there is no need to use the current admin for login anymore.

2024-09-23 06:25 UTC, vin0401 approved these changes
Looks good. :)

2024-09-23 07:09 UTC, merged