Prepare data object context and properties tab
pimcore/studio-ui-bundle pull request #545
Opened 2024-09-20 12:40 UTC by markus-moser

2024-09-30 10:36 UTC, vin0401 requested changes
Just one small thing with the component registry. 
Apart from that it's super awesome to see the first steps for the objects! :)

2024-09-30 10:36 UTC, vin0401 commented on assets/js/src/core/app/config/services/index.ts
> +container.bind(serviceIds['DataObject/Editor/ComponentRegistry']).to(ComponentRegistryService).inSingletonScope()
To be honest I'm not sure why this one was bound initially to the assets. 
It should be generic for all case.

2024-09-30 10:51 UTC, markus-moser commented on assets/js/src/core/app/config/services/index.ts
> +container.bind(serviceIds['DataObject/Editor/ComponentRegistry']).to(ComponentRegistryService).inSingletonScope()
Should it be in the element context or totally global for all kind of components?

2024-09-30 10:54 UTC, vin0401 commented on assets/js/src/core/app/config/services/index.ts
> +container.bind(serviceIds['DataObject/Editor/ComponentRegistry']).to(ComponentRegistryService).inSingletonScope()
I would make it totally global. So far I would not see the benefit to limit it to a specific area. 
The components are registered via a descriptive identifier, anyway.

2024-10-02 10:14 UTC, merged

2024-10-02 12:52 UTC, markus-moser commented on assets/js/src/core/app/config/services/index.ts
> +container.bind(serviceIds['DataObject/Editor/ComponentRegistry']).to(ComponentRegistryService).inSingletonScope()
Fixed in #563