The MiniPaint integration
pimcore/studio-ui-bundle pull request #817
Opened 2024-12-11 10:05 UTC by ValeriaMaltseva

Task: https://github.com/pimcore/studio-ui-bundle/issues/740

2025-01-09 13:44 UTC, vin0401 requested changes
I saw that you introduced a new folder called services. 
I'm not sure what the purpose/meaning of this folder is.

Could elaborate a bit on that?
Right now, we already have a lib folder maybe that one would also be suitable not sure.

For me services are more like useful classes/objects that are provided via our dependency injection container. So I'm not sure if the name is really suitable in that case.

2025-01-13 15:01 UTC, vin0401 approved these changes

2025-01-13 15:22 UTC, markus-moser commented on templates/image-editor/editor.html.twig
> +            body: JSON.stringify({ locale: 'en', keys: [] })
We should add the requested translation keys here in the keys array. With this approach we would only get the relevant translation keys instead of the full list.

2025-01-13 15:25 UTC, markus-moser commented
@ValeriaMaltseva Only found one small topic (see my comment). Other then that I tested it a bit and everything seems to be fine. We can merge it after checking my comment. 👍

2025-01-14 10:01 UTC, merged